// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/automl/v1beta1/translation.proto

#ifndef PROTOBUF_INCLUDED_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto
#define PROTOBUF_INCLUDED_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include "google/cloud/automl/v1beta1/data_items.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto 

namespace protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto
namespace google {
namespace cloud {
namespace automl {
namespace v1beta1 {
class TranslationAnnotation;
class TranslationAnnotationDefaultTypeInternal;
extern TranslationAnnotationDefaultTypeInternal _TranslationAnnotation_default_instance_;
class TranslationDatasetMetadata;
class TranslationDatasetMetadataDefaultTypeInternal;
extern TranslationDatasetMetadataDefaultTypeInternal _TranslationDatasetMetadata_default_instance_;
class TranslationEvaluationMetrics;
class TranslationEvaluationMetricsDefaultTypeInternal;
extern TranslationEvaluationMetricsDefaultTypeInternal _TranslationEvaluationMetrics_default_instance_;
class TranslationModelMetadata;
class TranslationModelMetadataDefaultTypeInternal;
extern TranslationModelMetadataDefaultTypeInternal _TranslationModelMetadata_default_instance_;
}  // namespace v1beta1
}  // namespace automl
}  // namespace cloud
}  // namespace google
namespace google {
namespace protobuf {
template<> ::google::cloud::automl::v1beta1::TranslationAnnotation* Arena::CreateMaybeMessage<::google::cloud::automl::v1beta1::TranslationAnnotation>(Arena*);
template<> ::google::cloud::automl::v1beta1::TranslationDatasetMetadata* Arena::CreateMaybeMessage<::google::cloud::automl::v1beta1::TranslationDatasetMetadata>(Arena*);
template<> ::google::cloud::automl::v1beta1::TranslationEvaluationMetrics* Arena::CreateMaybeMessage<::google::cloud::automl::v1beta1::TranslationEvaluationMetrics>(Arena*);
template<> ::google::cloud::automl::v1beta1::TranslationModelMetadata* Arena::CreateMaybeMessage<::google::cloud::automl::v1beta1::TranslationModelMetadata>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace google {
namespace cloud {
namespace automl {
namespace v1beta1 {

// ===================================================================

class TranslationDatasetMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.automl.v1beta1.TranslationDatasetMetadata) */ {
 public:
  TranslationDatasetMetadata();
  virtual ~TranslationDatasetMetadata();

  TranslationDatasetMetadata(const TranslationDatasetMetadata& from);

  inline TranslationDatasetMetadata& operator=(const TranslationDatasetMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TranslationDatasetMetadata(TranslationDatasetMetadata&& from) noexcept
    : TranslationDatasetMetadata() {
    *this = ::std::move(from);
  }

  inline TranslationDatasetMetadata& operator=(TranslationDatasetMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TranslationDatasetMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TranslationDatasetMetadata* internal_default_instance() {
    return reinterpret_cast<const TranslationDatasetMetadata*>(
               &_TranslationDatasetMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TranslationDatasetMetadata* other);
  friend void swap(TranslationDatasetMetadata& a, TranslationDatasetMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TranslationDatasetMetadata* New() const final {
    return CreateMaybeMessage<TranslationDatasetMetadata>(NULL);
  }

  TranslationDatasetMetadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TranslationDatasetMetadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TranslationDatasetMetadata& from);
  void MergeFrom(const TranslationDatasetMetadata& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TranslationDatasetMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string source_language_code = 1;
  void clear_source_language_code();
  static const int kSourceLanguageCodeFieldNumber = 1;
  const ::std::string& source_language_code() const;
  void set_source_language_code(const ::std::string& value);
  #if LANG_CXX11
  void set_source_language_code(::std::string&& value);
  #endif
  void set_source_language_code(const char* value);
  void set_source_language_code(const char* value, size_t size);
  ::std::string* mutable_source_language_code();
  ::std::string* release_source_language_code();
  void set_allocated_source_language_code(::std::string* source_language_code);

  // string target_language_code = 2;
  void clear_target_language_code();
  static const int kTargetLanguageCodeFieldNumber = 2;
  const ::std::string& target_language_code() const;
  void set_target_language_code(const ::std::string& value);
  #if LANG_CXX11
  void set_target_language_code(::std::string&& value);
  #endif
  void set_target_language_code(const char* value);
  void set_target_language_code(const char* value, size_t size);
  ::std::string* mutable_target_language_code();
  ::std::string* release_target_language_code();
  void set_allocated_target_language_code(::std::string* target_language_code);

  // @@protoc_insertion_point(class_scope:google.cloud.automl.v1beta1.TranslationDatasetMetadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr source_language_code_;
  ::google::protobuf::internal::ArenaStringPtr target_language_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TranslationEvaluationMetrics : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.automl.v1beta1.TranslationEvaluationMetrics) */ {
 public:
  TranslationEvaluationMetrics();
  virtual ~TranslationEvaluationMetrics();

  TranslationEvaluationMetrics(const TranslationEvaluationMetrics& from);

  inline TranslationEvaluationMetrics& operator=(const TranslationEvaluationMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TranslationEvaluationMetrics(TranslationEvaluationMetrics&& from) noexcept
    : TranslationEvaluationMetrics() {
    *this = ::std::move(from);
  }

  inline TranslationEvaluationMetrics& operator=(TranslationEvaluationMetrics&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TranslationEvaluationMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TranslationEvaluationMetrics* internal_default_instance() {
    return reinterpret_cast<const TranslationEvaluationMetrics*>(
               &_TranslationEvaluationMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TranslationEvaluationMetrics* other);
  friend void swap(TranslationEvaluationMetrics& a, TranslationEvaluationMetrics& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TranslationEvaluationMetrics* New() const final {
    return CreateMaybeMessage<TranslationEvaluationMetrics>(NULL);
  }

  TranslationEvaluationMetrics* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TranslationEvaluationMetrics>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TranslationEvaluationMetrics& from);
  void MergeFrom(const TranslationEvaluationMetrics& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TranslationEvaluationMetrics* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double bleu_score = 1;
  void clear_bleu_score();
  static const int kBleuScoreFieldNumber = 1;
  double bleu_score() const;
  void set_bleu_score(double value);

  // double base_bleu_score = 2;
  void clear_base_bleu_score();
  static const int kBaseBleuScoreFieldNumber = 2;
  double base_bleu_score() const;
  void set_base_bleu_score(double value);

  // @@protoc_insertion_point(class_scope:google.cloud.automl.v1beta1.TranslationEvaluationMetrics)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double bleu_score_;
  double base_bleu_score_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TranslationModelMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.automl.v1beta1.TranslationModelMetadata) */ {
 public:
  TranslationModelMetadata();
  virtual ~TranslationModelMetadata();

  TranslationModelMetadata(const TranslationModelMetadata& from);

  inline TranslationModelMetadata& operator=(const TranslationModelMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TranslationModelMetadata(TranslationModelMetadata&& from) noexcept
    : TranslationModelMetadata() {
    *this = ::std::move(from);
  }

  inline TranslationModelMetadata& operator=(TranslationModelMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TranslationModelMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TranslationModelMetadata* internal_default_instance() {
    return reinterpret_cast<const TranslationModelMetadata*>(
               &_TranslationModelMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(TranslationModelMetadata* other);
  friend void swap(TranslationModelMetadata& a, TranslationModelMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TranslationModelMetadata* New() const final {
    return CreateMaybeMessage<TranslationModelMetadata>(NULL);
  }

  TranslationModelMetadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TranslationModelMetadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TranslationModelMetadata& from);
  void MergeFrom(const TranslationModelMetadata& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TranslationModelMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string base_model = 1;
  void clear_base_model();
  static const int kBaseModelFieldNumber = 1;
  const ::std::string& base_model() const;
  void set_base_model(const ::std::string& value);
  #if LANG_CXX11
  void set_base_model(::std::string&& value);
  #endif
  void set_base_model(const char* value);
  void set_base_model(const char* value, size_t size);
  ::std::string* mutable_base_model();
  ::std::string* release_base_model();
  void set_allocated_base_model(::std::string* base_model);

  // string source_language_code = 2;
  void clear_source_language_code();
  static const int kSourceLanguageCodeFieldNumber = 2;
  const ::std::string& source_language_code() const;
  void set_source_language_code(const ::std::string& value);
  #if LANG_CXX11
  void set_source_language_code(::std::string&& value);
  #endif
  void set_source_language_code(const char* value);
  void set_source_language_code(const char* value, size_t size);
  ::std::string* mutable_source_language_code();
  ::std::string* release_source_language_code();
  void set_allocated_source_language_code(::std::string* source_language_code);

  // string target_language_code = 3;
  void clear_target_language_code();
  static const int kTargetLanguageCodeFieldNumber = 3;
  const ::std::string& target_language_code() const;
  void set_target_language_code(const ::std::string& value);
  #if LANG_CXX11
  void set_target_language_code(::std::string&& value);
  #endif
  void set_target_language_code(const char* value);
  void set_target_language_code(const char* value, size_t size);
  ::std::string* mutable_target_language_code();
  ::std::string* release_target_language_code();
  void set_allocated_target_language_code(::std::string* target_language_code);

  // @@protoc_insertion_point(class_scope:google.cloud.automl.v1beta1.TranslationModelMetadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr base_model_;
  ::google::protobuf::internal::ArenaStringPtr source_language_code_;
  ::google::protobuf::internal::ArenaStringPtr target_language_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TranslationAnnotation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.cloud.automl.v1beta1.TranslationAnnotation) */ {
 public:
  TranslationAnnotation();
  virtual ~TranslationAnnotation();

  TranslationAnnotation(const TranslationAnnotation& from);

  inline TranslationAnnotation& operator=(const TranslationAnnotation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TranslationAnnotation(TranslationAnnotation&& from) noexcept
    : TranslationAnnotation() {
    *this = ::std::move(from);
  }

  inline TranslationAnnotation& operator=(TranslationAnnotation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TranslationAnnotation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TranslationAnnotation* internal_default_instance() {
    return reinterpret_cast<const TranslationAnnotation*>(
               &_TranslationAnnotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(TranslationAnnotation* other);
  friend void swap(TranslationAnnotation& a, TranslationAnnotation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TranslationAnnotation* New() const final {
    return CreateMaybeMessage<TranslationAnnotation>(NULL);
  }

  TranslationAnnotation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TranslationAnnotation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TranslationAnnotation& from);
  void MergeFrom(const TranslationAnnotation& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TranslationAnnotation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.cloud.automl.v1beta1.TextSnippet translated_content = 1;
  bool has_translated_content() const;
  void clear_translated_content();
  static const int kTranslatedContentFieldNumber = 1;
  private:
  const ::google::cloud::automl::v1beta1::TextSnippet& _internal_translated_content() const;
  public:
  const ::google::cloud::automl::v1beta1::TextSnippet& translated_content() const;
  ::google::cloud::automl::v1beta1::TextSnippet* release_translated_content();
  ::google::cloud::automl::v1beta1::TextSnippet* mutable_translated_content();
  void set_allocated_translated_content(::google::cloud::automl::v1beta1::TextSnippet* translated_content);

  // @@protoc_insertion_point(class_scope:google.cloud.automl.v1beta1.TranslationAnnotation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::cloud::automl::v1beta1::TextSnippet* translated_content_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TranslationDatasetMetadata

// string source_language_code = 1;
inline void TranslationDatasetMetadata::clear_source_language_code() {
  source_language_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TranslationDatasetMetadata::source_language_code() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
  return source_language_code_.GetNoArena();
}
inline void TranslationDatasetMetadata::set_source_language_code(const ::std::string& value) {
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
}
#if LANG_CXX11
inline void TranslationDatasetMetadata::set_source_language_code(::std::string&& value) {
  
  source_language_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
}
#endif
inline void TranslationDatasetMetadata::set_source_language_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
}
inline void TranslationDatasetMetadata::set_source_language_code(const char* value, size_t size) {
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
}
inline ::std::string* TranslationDatasetMetadata::mutable_source_language_code() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
  return source_language_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TranslationDatasetMetadata::release_source_language_code() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
  
  return source_language_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TranslationDatasetMetadata::set_allocated_source_language_code(::std::string* source_language_code) {
  if (source_language_code != NULL) {
    
  } else {
    
  }
  source_language_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_language_code);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationDatasetMetadata.source_language_code)
}

// string target_language_code = 2;
inline void TranslationDatasetMetadata::clear_target_language_code() {
  target_language_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TranslationDatasetMetadata::target_language_code() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
  return target_language_code_.GetNoArena();
}
inline void TranslationDatasetMetadata::set_target_language_code(const ::std::string& value) {
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
}
#if LANG_CXX11
inline void TranslationDatasetMetadata::set_target_language_code(::std::string&& value) {
  
  target_language_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
}
#endif
inline void TranslationDatasetMetadata::set_target_language_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
}
inline void TranslationDatasetMetadata::set_target_language_code(const char* value, size_t size) {
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
}
inline ::std::string* TranslationDatasetMetadata::mutable_target_language_code() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
  return target_language_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TranslationDatasetMetadata::release_target_language_code() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
  
  return target_language_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TranslationDatasetMetadata::set_allocated_target_language_code(::std::string* target_language_code) {
  if (target_language_code != NULL) {
    
  } else {
    
  }
  target_language_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_language_code);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationDatasetMetadata.target_language_code)
}

// -------------------------------------------------------------------

// TranslationEvaluationMetrics

// double bleu_score = 1;
inline void TranslationEvaluationMetrics::clear_bleu_score() {
  bleu_score_ = 0;
}
inline double TranslationEvaluationMetrics::bleu_score() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationEvaluationMetrics.bleu_score)
  return bleu_score_;
}
inline void TranslationEvaluationMetrics::set_bleu_score(double value) {
  
  bleu_score_ = value;
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationEvaluationMetrics.bleu_score)
}

// double base_bleu_score = 2;
inline void TranslationEvaluationMetrics::clear_base_bleu_score() {
  base_bleu_score_ = 0;
}
inline double TranslationEvaluationMetrics::base_bleu_score() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationEvaluationMetrics.base_bleu_score)
  return base_bleu_score_;
}
inline void TranslationEvaluationMetrics::set_base_bleu_score(double value) {
  
  base_bleu_score_ = value;
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationEvaluationMetrics.base_bleu_score)
}

// -------------------------------------------------------------------

// TranslationModelMetadata

// string base_model = 1;
inline void TranslationModelMetadata::clear_base_model() {
  base_model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TranslationModelMetadata::base_model() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
  return base_model_.GetNoArena();
}
inline void TranslationModelMetadata::set_base_model(const ::std::string& value) {
  
  base_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
}
#if LANG_CXX11
inline void TranslationModelMetadata::set_base_model(::std::string&& value) {
  
  base_model_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
}
#endif
inline void TranslationModelMetadata::set_base_model(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  base_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
}
inline void TranslationModelMetadata::set_base_model(const char* value, size_t size) {
  
  base_model_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
}
inline ::std::string* TranslationModelMetadata::mutable_base_model() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
  return base_model_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TranslationModelMetadata::release_base_model() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
  
  return base_model_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TranslationModelMetadata::set_allocated_base_model(::std::string* base_model) {
  if (base_model != NULL) {
    
  } else {
    
  }
  base_model_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), base_model);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationModelMetadata.base_model)
}

// string source_language_code = 2;
inline void TranslationModelMetadata::clear_source_language_code() {
  source_language_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TranslationModelMetadata::source_language_code() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
  return source_language_code_.GetNoArena();
}
inline void TranslationModelMetadata::set_source_language_code(const ::std::string& value) {
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
}
#if LANG_CXX11
inline void TranslationModelMetadata::set_source_language_code(::std::string&& value) {
  
  source_language_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
}
#endif
inline void TranslationModelMetadata::set_source_language_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
}
inline void TranslationModelMetadata::set_source_language_code(const char* value, size_t size) {
  
  source_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
}
inline ::std::string* TranslationModelMetadata::mutable_source_language_code() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
  return source_language_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TranslationModelMetadata::release_source_language_code() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
  
  return source_language_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TranslationModelMetadata::set_allocated_source_language_code(::std::string* source_language_code) {
  if (source_language_code != NULL) {
    
  } else {
    
  }
  source_language_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_language_code);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationModelMetadata.source_language_code)
}

// string target_language_code = 3;
inline void TranslationModelMetadata::clear_target_language_code() {
  target_language_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TranslationModelMetadata::target_language_code() const {
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
  return target_language_code_.GetNoArena();
}
inline void TranslationModelMetadata::set_target_language_code(const ::std::string& value) {
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
}
#if LANG_CXX11
inline void TranslationModelMetadata::set_target_language_code(::std::string&& value) {
  
  target_language_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
}
#endif
inline void TranslationModelMetadata::set_target_language_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
}
inline void TranslationModelMetadata::set_target_language_code(const char* value, size_t size) {
  
  target_language_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
}
inline ::std::string* TranslationModelMetadata::mutable_target_language_code() {
  
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
  return target_language_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TranslationModelMetadata::release_target_language_code() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
  
  return target_language_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TranslationModelMetadata::set_allocated_target_language_code(::std::string* target_language_code) {
  if (target_language_code != NULL) {
    
  } else {
    
  }
  target_language_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_language_code);
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationModelMetadata.target_language_code)
}

// -------------------------------------------------------------------

// TranslationAnnotation

// .google.cloud.automl.v1beta1.TextSnippet translated_content = 1;
inline bool TranslationAnnotation::has_translated_content() const {
  return this != internal_default_instance() && translated_content_ != NULL;
}
inline const ::google::cloud::automl::v1beta1::TextSnippet& TranslationAnnotation::_internal_translated_content() const {
  return *translated_content_;
}
inline const ::google::cloud::automl::v1beta1::TextSnippet& TranslationAnnotation::translated_content() const {
  const ::google::cloud::automl::v1beta1::TextSnippet* p = translated_content_;
  // @@protoc_insertion_point(field_get:google.cloud.automl.v1beta1.TranslationAnnotation.translated_content)
  return p != NULL ? *p : *reinterpret_cast<const ::google::cloud::automl::v1beta1::TextSnippet*>(
      &::google::cloud::automl::v1beta1::_TextSnippet_default_instance_);
}
inline ::google::cloud::automl::v1beta1::TextSnippet* TranslationAnnotation::release_translated_content() {
  // @@protoc_insertion_point(field_release:google.cloud.automl.v1beta1.TranslationAnnotation.translated_content)
  
  ::google::cloud::automl::v1beta1::TextSnippet* temp = translated_content_;
  translated_content_ = NULL;
  return temp;
}
inline ::google::cloud::automl::v1beta1::TextSnippet* TranslationAnnotation::mutable_translated_content() {
  
  if (translated_content_ == NULL) {
    auto* p = CreateMaybeMessage<::google::cloud::automl::v1beta1::TextSnippet>(GetArenaNoVirtual());
    translated_content_ = p;
  }
  // @@protoc_insertion_point(field_mutable:google.cloud.automl.v1beta1.TranslationAnnotation.translated_content)
  return translated_content_;
}
inline void TranslationAnnotation::set_allocated_translated_content(::google::cloud::automl::v1beta1::TextSnippet* translated_content) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(translated_content_);
  }
  if (translated_content) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      translated_content = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, translated_content, submessage_arena);
    }
    
  } else {
    
  }
  translated_content_ = translated_content;
  // @@protoc_insertion_point(field_set_allocated:google.cloud.automl.v1beta1.TranslationAnnotation.translated_content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1beta1
}  // namespace automl
}  // namespace cloud
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_google_2fcloud_2fautoml_2fv1beta1_2ftranslation_2eproto
